#pragma once

enum class Error : uint8_t {
  OK,
  ALREADY_CONNECTED,
  CONNECTION_FAILED,
  SERVER_FINGERPRINT_NOT_FOUND,
  CONNECT_NO_MEMORY,

  // ConnAck Errors
  UNSUPPORTED_SERVER_VERSION,
  IDENTIFIER_REJECTED,
  SERVER_UNAVAILABLE,
  PROTOCOL_ERROR,
  NOT_AUTHORIZED,

  // tcp errors

  TCP_OUT_OF_MEMORY,
  TCP_BUFFER_ERROR,
  TCP_TIMEOUT,
  TCP_ROUTING,
  CONNECTION_ABORTED,
  CONNECTION_RESET,
  CONNECTION_CLOSED,
  TCP_LOW_LEVEL,
  DNS_ERROR,
  TCP_UNKNOWN,
};
